# Any snapshot for GHC >= 7.10 should work, we pick a recent stable one:
# (recent as of 2022-12-07)
resolver: lts-20.3

# See https://www.stackage.org/ "Latest releases per GHC version"
# for alternatives.
