# Any snapshot for GHC >= 7.10 should work, we pick a recent stable one:
# (recent as of 2022-10-31)
resolver: lts-18.28

# See https://www.stackage.org/ "Latest releases per GHC version"
# for alternatives.
